export const weatherData = [
    {
        "id": 1,
        "location": "Buenos Aires",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 2,
        "location": "Jujuy",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 3,
        "location": "Salta",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 4,
        "location": "Tucuman",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 5,
        "location": "Santiago del Estero",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 6,
        "location": "Córdoba",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 7,
        "location": "Corrientes",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 8,
        "location": "Chaco",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    },
    {
        "id": 9,
        "location": "Santa fe",
        "latitude": 52.25,
        "longitude": 10.25,
        "temperature": 25,
        "windSpeed": 10,
    }
]
